In [2]:
import numpy as np

In [3]:
array_2d = np.array([[1,2,3],[4,5,6]])
print("\n2D Array:\n", array_2d)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
array_3d= np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print("\n3D Array: \n", array_3d)


3D Array: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
print("\nArray Properties:")
print("Shape:", array_2d.shape)
print("Size:", array_2d.size)
print("Data Type:", array_2d.dtype)


Array Properties:
Shape: (2, 3)
Size: 6
Data Type: int32


In [7]:
zeros = np.zeros((2,3))
print("\nZeros Array:\n", zeros)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
zeros = np.ones((2,3))
print("\nZeros Array:\n", zeros)


Zeros Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
arange_array = np.arange(0, 100, 20)
print(arange_array)

[ 0 20 40 60 80]


In [11]:
array_a = np.array([1,2,3])
arrat_b = np.array([4,5,6])
add = array_a + arrat_b
print(add)

[5 7 9]


In [12]:
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[5,6],[7,8]])
product = np.dot(matrix_a, matrix_b)
print(product)

[[19 22]
 [43 50]]


In [18]:
array = np.array([1,2,3,4,5,6,7,8,9])
print("\nStatistical Operations")
print("Sum", array.sum())
print("Mean",array.mean())
print("SD:",array.std())
print("Max:", array.max())
print("Min:", array.min())


Statistical Operations
Sum 45
Mean 5.0
SD: 2.581988897471611
Max: 9
Min: 1


In [19]:
r_array = np.random.random((2,3))
print(r_array)

[[0.17929501 0.42280542 0.04614756]
 [0.89371447 0.83339902 0.02963269]]
